#ifndef DEF_INTERNALNOTICEPRIORITIES_H
#define DEF_INTERNALNOTICEPRIORITIES_H

#define INP_DEFAULT                  500
#define INP_GATEWAYS_CONFLICT        800

#endif // DEF_INTERNALNOTICEPRIORITIES_H
