#ifndef DEF_MESSAGEHANDLERORDERS_H
#define DEF_MESSAGEHANDLERORDERS_H

#define MHO_SMSMESSAGEHANDLER                 500
#define MHO_CHATMESSAGEHANDLER                900

#endif // DEF_MESSAGEHANDLERORDERS_H
