#ifndef DEF_MESSAGEHANDLERORDERS_H
#define DEF_MESSAGEHANDLERORDERS_H

#define MHO_MULTIUSERCHAT_INVITE              500
#define MHO_MULTIUSERCHAT_GROUPCHAT           600
#define MHO_SMSMESSAGEHANDLER                 700
#define MHO_CHATMESSAGEHANDLER                900

#endif // DEF_MESSAGEHANDLERORDERS_H
