#ifndef DEF_NOTIFICATIONDATAROLES_H
#define DEF_NOTIFICATIONDATAROLES_H

enum NotificationDataRoles {
	NDR_STREAM_JID,
	NDR_CONTACT_JID,
	NDR_ICON,
	NDR_ICON_KEY,
	NDR_ICON_STORAGE,
	NDR_ROSTER_ORDER,
	NDR_ROSTER_FLAGS,
	NDR_ROSTER_TIMEOUT,
	NDR_ROSTER_HOOK_CLICK,
	NDR_ROSTER_CREATE_INDEX,
	NDR_ROSTER_FOOTER,
	NDR_ROSTER_BACKGROUND,
	NDR_POPUP_ICON,
	NDR_POPUP_TITLE,
	NDR_POPUP_CAPTION,
	NDR_POPUP_NOTICE,
	NDR_POPUP_IMAGE,
	NDR_POPUP_TEXT,
	NDR_POPUP_TIMEOUT,
	NDR_POPUP_STYLEKEY,
	NDR_POPUP_CAN_ACTIVATE,
	NDR_TRAY_TOOLTIP,
	NDR_SOUND_FILE,
	NDR_TABPAGE_PRIORITY,
	NDR_TABPAGE_NOTIFYCOUNT,
	NDR_TABPAGE_ICONBLINK,
	NDR_TABPAGE_CREATE_TAB,
	NDR_TABPAGE_ALERT_WINDOW,
	NDR_TABPAGE_TOOLTIP,
	NDR_TABPAGE_STYLEKEY,
	NDR_REPLACE_NOTIFY,
	NDR_USER_ROLES = 32,
	NDR_SUBSCRIPTION_TYPE,
	NDR_SUBSCRIPTION_TEXT
};

#endif
