#ifndef DEF_ROSTERPROXYORDERS_H
#define DEF_ROSTERPROXYORDERS_H

#define RPO_METACONTACTS_MODIFIER         100
#define RPO_ROSTERSVIEW_NOGROUPS          200
#define RPO_ROSTERSEARCH_FILTER           400
#define RPO_GATEWAYS_ACCOUNT_FILTER       500
#define RPO_ROSTERSVIEW_SORTFILTER        1000

#endif // DEF_ROSTERPROXYORDERS_H
