#ifndef DEF_TABPAGENOTIFYPRIORITIES_H
#define DEF_TABPAGENOTIFYPRIORITIES_H

#define TPNP_SIP_CALL             100
#define TPNP_CHATSTATE_TYPING     200
#define TPNP_SUBSCRIPTION         400
#define TPNP_NEW_MESSAGE          600

#endif
