#!/bin/bash
cd /Applications

appname=Contacts.app

# usage: "patchFile file frameworkName"
function patchFile {
	# file to patch
	file=$1
	# frmework
	FW=$2
	# patching...
	install_name_tool -change $FW.framework/Versions/Current/$FW @executable_path/../Frameworks/$FW.framework/Versions/Current/$FW $appname/Contents/$file
}

# Contacts deps - core, network, gui, multimedia, xml, xmlpatterns, webkit, phonon, growl, sparkle

patchFile MacOS/Contacts QtNetwork
patchFile MacOS/Contacts QtCore
patchFile MacOS/Contacts QtGui
patchFile MacOS/Contacts QtMultimedia
patchFile MacOS/Contacts QtXml
patchFile MacOS/Contacts QtXmlPatterns
patchFile MacOS/Contacts QtWebKit
patchFile MacOS/Contacts phonon
patchFile MacOS/Contacts Growl
patchFile MacOS/Contacts Sparkle

# utils deps - core, gui, xml, webkit, network

patchFile Frameworks/libramblercontactsutils.1.dylib QtCore
patchFile Frameworks/libramblercontactsutils.1.dylib QtXml
patchFile Frameworks/libramblercontactsutils.1.dylib QtGui
patchFile Frameworks/libramblercontactsutils.1.dylib QtWebKit
patchFile Frameworks/libramblercontactsutils.1.dylib QtNetwork

# phonon deps - gui, core, xml, dbus

patchFile Frameworks/phonon.framework/Versions/4/phonon QtCore
patchFile Frameworks/phonon.framework/Versions/4/phonon QtGui
patchFile Frameworks/phonon.framework/Versions/4/phonon QtXml
patchFile Frameworks/phonon.framework/Versions/4/phonon QtDBus

# gui deps - core

patchFile Frameworks/QtGui.framework/Versions/4/QtGui QtCore

# network deps - core

patchFile Frameworks/QtNetwork.framework/Versions/4/QtNetwork QtCore

# mm deps - core, gui

patchFile Frameworks/QtMultimedia.framework/Versions/4/QtMultimedia QtCore
patchFile Frameworks/QtMultimedia.framework/Versions/4/QtMultimedia QtGui

# xml deps - core

patchFile Frameworks/QtXml.framework/Versions/4/QtXml QtCore

# xmlpat deps - core, network

patchFile Frameworks/QtXmlPatterns.framework/Versions/4/QtXmlPatterns QtCore
patchFile Frameworks/QtXmlPatterns.framework/Versions/4/QtXmlPatterns QtNetwork

# dbus deps - xml, core

patchFile Frameworks/QtDBus.framework/Versions/4/QtDBus QtCore
patchFile Frameworks/QtDBus.framework/Versions/4/QtDBus QtXml

# webkit deps - core, gui, xml, dbus, phonon, network

patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit QtCore
patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit QtGui
patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit QtXml
patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit phonon
patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit QtDBus
patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit QtNetwork

# plugins deps - core, gui, xml, xmlpatterns, network, webkit, phonon, growl, sparkle

for i in $(ls $appname/Contents/PlugIns/); do

	echo patching $appname/Contents/Plugins/$i

	patchFile Plugins/$i QtCore
	patchFile Plugins/$i QtGui
	patchFile Plugins/$i QtNetwork
	patchFile Plugins/$i QtWebKit
	patchFile Plugins/$i QtXml
	patchFile Plugins/$i QtXmlPatterns
	patchFile Plugins/$i phonon
	patchFile Plugins/$i Growl
	patchFile Plugins/$i Sparkle

done
