#!/bin/bash
cd /Applications

appname=ramblercontacts.app

# copy qt frameworks

qtpath=/Library/Frameworks

qtapppath=$appname/Contents/Frameworks
mkdir $qtapppath

function copyqt {
	# copy all
	echo copying $1...
	cp -R $qtpath/$1.framework $qtapppath/
	#remove debug libs
	cd $qtapppath/$1.framework
	rm -rf $1_debug.dSYM
	rm -f $1_debug
	rm -f $1_debug.prl
	cd Versions/4/
	rm -f $1_debug
	rm -rf Headers
	# return to apps dir
	cd /Applications
}

copyqt QtCore
copyqt QtGui
copyqt QtNetwork
copyqt QtMultimedia
copyqt QtXml
copyqt QtXmlPatterns
copyqt QtWebKit
copyqt QtDBus
copyqt phonon
