#!/bin/bash
cd /Applications

appname=ramblercontacts.app

# usage: "patchFile MacOS/file QtNetwork"
function patchFile {
	# file to patch
	file=$1
	# Qt Module
	QM=$2
	# patching...
	install_name_tool -change $QM.framework/Versions/4/$QM @executable_path/../Frameworks/$QM.framework/Versions/4/$QM $appname/Contents/$file
}

# ramblercontacts

patchFile MacOS/ramblercontacts QtNetwork
patchFile MacOS/ramblercontacts QtCore
patchFile MacOS/ramblercontacts QtGui
patchFile MacOS/ramblercontacts QtMultimedia
patchFile MacOS/ramblercontacts QtXml
patchFile MacOS/ramblercontacts QtXmlPatterns
patchFile MacOS/ramblercontacts QtWebKit
patchFile MacOS/ramblercontacts phonon

# utils deps - core, gui, xml, webkit

patchFile Frameworks/libramblercontactsutils.1.dylib QtCore
patchFile Frameworks/libramblercontactsutils.1.dylib QtXml
patchFile Frameworks/libramblercontactsutils.1.dylib QtGui
patchFile Frameworks/libramblercontactsutils.1.dylib QtWebKit

# phonon deps - gui, core, xml, dbus

patchFile Frameworks/phonon.framework/Versions/4/phonon QtCore
patchFile Frameworks/phonon.framework/Versions/4/phonon QtGui
patchFile Frameworks/phonon.framework/Versions/4/phonon QtXml
patchFile Frameworks/phonon.framework/Versions/4/phonon QtDBus

# gui deps - core

patchFile Frameworks/QtGui.framework/Versions/4/QtGui QtCore

# network deps - core

patchFile Frameworks/QtNetwork.framework/Versions/4/QtNetwork QtCore

# mm deps - core, gui

patchFile Frameworks/QtMultimedia.framework/Versions/4/QtMultimedia QtCore
patchFile Frameworks/QtMultimedia.framework/Versions/4/QtMultimedia QtGui

# xml deps - core

patchFile Frameworks/QtXml.framework/Versions/4/QtXml QtCore

# xmlpat deps - core, network

patchFile Frameworks/QtXmlPatterns.framework/Versions/4/QtXmlPatterns QtCore
patchFile Frameworks/QtXmlPatterns.framework/Versions/4/QtXmlPatterns QtNetwork

# dbus deps - xml, core

patchFile Frameworks/QtDBus.framework/Versions/4/QtDBus QtCore
patchFile Frameworks/QtDBus.framework/Versions/4/QtDBus QtXml

# webkit deps - core, gui, xml, dbus, phonon, network

patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit QtCore
patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit QtGui
patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit QtXml
patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit phonon
patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit QtDBus
patchFile Frameworks/QtWebKit.framework/Versions/4/QtWebKit QtNetwork

# plugins deps - core, gui, xml, network, webkit

for i in $(ls $appname/Contents/PlugIns/); do

echo patching $appname/Contents/Plugins/$i

patchFile Plugins/$i QtCore
patchFile Plugins/$i QtGui
patchFile Plugins/$i QtNetwork
patchFile Plugins/$i QtWebKit
patchFile Plugins/$i QtXml
patchFile Plugins/$i QtXmlPatterns
patchFile Plugins/$i phonon

done
