#!/bin/bash
cd /Applications

appname=Contacts.app

# copy qt frameworks

frameworkspath=/Library/Frameworks

qtapppath=$appname/Contents/Frameworks
mkdir $qtapppath

function copyframework {
	# copy all
	echo copying $1...
	cp -R $frameworkspath/$1.framework $qtapppath/
	#remove debug libs
	cd $qtapppath/$1.framework
	rm -rf $1_debug.dSYM
	rm -f $1_debug
	rm -f $1_debug.prl
	cd Versions/Current/
	rm -f $1_debug
	rm -rf Headers
	# return to apps dir
	cd /Applications
}

copyframework QtCore
copyframework QtGui
copyframework QtNetwork
copyframework QtMultimedia
copyframework QtXml
copyframework QtXmlPatterns
copyframework QtWebKit
copyframework QtDBus
copyframework phonon
copyframework Growl
copyframework Sparkle
